[package]
name = "hal_aarch64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal_core = { path = "../hal_core" }
tock-registers = "0.7.x"
cortex-a = "7.4.0"
